/**
 * Session Export Module
 * Exports interview sessions as Markdown, JSON, or clipboard text.
 */

interface ExportableSession {
    id: string;
    startTime: string;
    endTime?: string;
    interviewType?: string;
    conversation?: Array<{
        speaker: string;
        text: string;
        timestamp?: string;
    }>;
    answers?: Array<{
        question: string;
        answer: string;
        source: string;
        timestamp?: string;
    }>;
    deliveryMetrics?: {
        wordsPerMinute?: number;
        fillerWordCount?: number;
        avgSentenceLength?: number;
        clarityScore?: number;
    };
    tags?: string[];
}

/**
 * Export a session as a formatted Markdown document.
 */
export function exportAsMarkdown(session: ExportableSession): string {
    const lines: string[] = [];

    // Header
    const date = new Date(session.startTime).toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    });
    const startTime = new Date(session.startTime).toLocaleTimeString('en-US', {
        hour: '2-digit', minute: '2-digit',
    });

    lines.push(`# Interview Session — ${date}`);
    lines.push(`> Started at ${startTime} • Type: ${session.interviewType || 'General'}${session.tags?.length ? ` • Tags: ${session.tags.join(', ')}` : ''}`);
    lines.push('');

    // Delivery Metrics
    if (session.deliveryMetrics) {
        const m = session.deliveryMetrics;
        lines.push('## 📊 Delivery Metrics');
        lines.push('| Metric | Value |');
        lines.push('|--------|-------|');
        if (m.wordsPerMinute) lines.push(`| Speaking Pace | ${m.wordsPerMinute} WPM |`);
        if (m.fillerWordCount !== undefined) lines.push(`| Filler Words | ${m.fillerWordCount} |`);
        if (m.avgSentenceLength) lines.push(`| Avg Sentence Length | ${m.avgSentenceLength} words |`);
        if (m.clarityScore) lines.push(`| Clarity Score | ${m.clarityScore}/10 |`);
        lines.push('');
    }

    // Transcript
    if (session.conversation && session.conversation.length > 0) {
        lines.push('## 🎙️ Transcript');
        lines.push('');
        for (const block of session.conversation) {
            const label = block.speaker === 'user' ? '**You**' : '**Interviewer**';
            const ts = block.timestamp ? ` *(${new Date(block.timestamp).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })})*` : '';
            lines.push(`${label}${ts}: ${block.text}`);
            lines.push('');
        }
    }

    // Q&A Pairs
    if (session.answers && session.answers.length > 0) {
        lines.push('## 💡 AI-Generated Answers');
        lines.push('');
        for (let i = 0; i < session.answers.length; i++) {
            const qa = session.answers[i];
            lines.push(`### Q${i + 1}: ${qa.question}`);
            lines.push(`*Source: ${qa.source}*`);
            lines.push('');
            lines.push(qa.answer);
            lines.push('');
            lines.push('---');
            lines.push('');
        }
    }

    // Footer
    lines.push('');
    lines.push('---');
    lines.push('*Generated by Synapse AI — Local-first Interview Copilot*');

    return lines.join('\n');
}

/**
 * Export as JSON for data portability.
 */
export function exportAsJSON(session: ExportableSession): string {
    return JSON.stringify(session, null, 2);
}

/**
 * Export as plain text (for clipboard).
 */
export function exportAsText(session: ExportableSession): string {
    const lines: string[] = [];

    lines.push(`Interview Session — ${new Date(session.startTime).toLocaleDateString()}`);
    lines.push(`Type: ${session.interviewType || 'General'}`);
    lines.push('');

    if (session.conversation && session.conversation.length > 0) {
        lines.push('=== TRANSCRIPT ===');
        for (const block of session.conversation) {
            const label = block.speaker === 'user' ? 'You' : 'Interviewer';
            lines.push(`[${label}] ${block.text}`);
        }
        lines.push('');
    }

    if (session.answers && session.answers.length > 0) {
        lines.push('=== AI ANSWERS ===');
        for (let i = 0; i < session.answers.length; i++) {
            const qa = session.answers[i];
            lines.push(`Q${i + 1}: ${qa.question}`);
            lines.push(`A: ${qa.answer}`);
            lines.push('');
        }
    }

    return lines.join('\n');
}

/**
 * Copy text to clipboard.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
    try {
        await navigator.clipboard.writeText(text);
        return true;
    } catch {
        return false;
    }
}

/**
 * Trigger a file download in the browser.
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
